from decimal import Decimal
from pathlib import Path
import re
from typing import Any, Tuple

from . import utils, drawmainsource, drawangsep

def fit_block_to_source_dict(fit_block: list[str]) -> Tuple[dict[str, str],dict[str, str]]:
    """Take a block for a measurement in a fit file an return the corresponding dictionary"""
    source_dict = {"is_main": ""}
    band_dict = {}
    for i, line in enumerate(fit_block):
        line = line.strip()
        if line.startswith("--- ra:") and not line.endswith("pixels"):
            matches = re.search(r"(?P<value>[0-9:\.]+)\s\+\/\-\s(?P<error>[0-9\.]+)\ss", line)
            source_dict["ra"] = matches.group("value")
            source_dict["ra_err"] = matches.group("error")
        elif line.startswith("--- dec:") and not line.endswith("pixels"):
            matches = re.search(r"(?P<value>\-?[0-9\.]+)\s\+\/\-\s(?P<error>[0-9\.]+)\sarcsec", line)
            source_dict["dec"] = utils.convert_dec(matches.group("value"))
            source_dict["dec_err"] = matches.group("error")
        elif line.startswith("Clean beam size"):
            matches = re.search(r"(?P<value>\-?[0-9\.]+)\sarcsec", fit_block[i+1].strip())
            band_dict["major"] = matches.group("value")
            matches = re.search(r"(?P<value>\-?[0-9\.]+)\sarcsec", fit_block[i+2].strip())
            band_dict["minor"] = matches.group("value")
        elif line.startswith("--- Integrated:"):
            matches = re.search(r"(?P<value>[0-9\.]+)\s\+\/\-\s(?P<error>[0-9\.]+\s[mu])Jy", line)
            if matches.group("error").endswith("u"):
                source_dict["flux"] = str(Decimal(matches.group("value"))/1000)
                source_dict["flux_err"] = str(Decimal(matches.group("error").strip("u "))/1000)
            else:                
                source_dict["flux"] = matches.group("value")
                source_dict["flux_err"] = matches.group("error").strip("m ")
        elif line.startswith("--- frequency:"):
            matches = re.search(r"(?P<value>[0-9\.]+)\sGHz", line)
            band_dict["freq"] = matches.group("value")
    return source_dict, band_dict


def fit_folder_to_dict(fit_folder: Path) -> dict[str,Any]:
    """Take the path of a folder containing fit files and return the corresponding dict"""
    fits_dict = {}
    for fit_file in fit_folder.iterdir():
        print(fit_file)
        with open(fit_file) as f:
            current_block = []
            for line in f:
                line = line.strip()
                # TODO: get date
                matches = re.search(r"_(?P<date>[0-9a-zA-Z]+)_(?P<band>[A-Za-z]+)band", fit_file.as_posix())
                fit_freq = matches.group("band")
                fit_date = matches.group("date")

                if not fits_dict.get(fit_date):
                    fits_dict[fit_date] = {
                        fit_freq: {}
                    }

                if not fits_dict[fit_date].get(fit_freq):
                    fits_dict[fit_date][fit_freq] = {}

                if line.startswith("Fit on"):
                    if current_block:
                        s_d, b_d = fit_block_to_source_dict(current_block)
                        fits_dict[fit_date][fit_freq]["data"] = b_d
                        if not fits_dict[fit_date][fit_freq].get("sources"):
                            fits_dict[fit_date][fit_freq]["sources"] = []
                        fits_dict[fit_date][fit_freq]["sources"].append(s_d)
                        current_block = []
                    current_block.append(line)

                elif current_block:
                    current_block.append(line)

            if current_block:
                s_d, b_d = fit_block_to_source_dict(current_block)
                fits_dict[fit_date][fit_freq]["data"] = b_d
                if not fits_dict[fit_date][fit_freq].get("sources"):
                    fits_dict[fit_date][fit_freq]["sources"] = []
                fits_dict[fit_date][fit_freq]["sources"].append(s_d)

    return fits_dict

def fit_dict_to_csv(fit_dict: dict[str,Any], filename: Path):
    """Take the dict generated by fit_folder_to_dict() and write it to the specified csv"""
    with open(filename, "w") as f:
        print(filename)
        for date, bands in fit_dict.items():
            for band, data_sources in bands.items():
                line = ",".join([
                    date,
                    band,
                    data_sources["data"]["freq"],
                    data_sources["data"]["major"],
                    data_sources["data"]["minor"],
                    *[",".join([
                        s["ra"],
                        s["ra_err"],
                        s["dec"],
                        s["dec_err"],
                        s["flux"],
                        s["flux_err"],
                        str(s["is_main"]),
                    ]) for s in data_sources["sources"]]
                ])
                f.write(line + "\n")

SOURCE_LEN = 7

def fit_csv_to_dict(fit_csv: Path):
    """Return a fit dict from a specified csv"""
    with open(fit_csv) as f:
        fits_dict = {}
        for line in f:
            line = line.strip().split(",")
            fit_date = line[0]
            fit_freq = line[1]
            if not fits_dict.get(fit_date):
                fits_dict[fit_date] = {
                    fit_freq: {}
                }
            if not fits_dict[fit_date].get(fit_freq):
                fits_dict[fit_date][fit_freq] = {}
            
            fits_dict[fit_date][fit_freq] ={
                "data": dict(zip(["freq", "major", "minor"], line[2:5]))
            }
            fits_dict[fit_date][fit_freq]["sources"] = []
            for i in range(5, len(line[5:]), SOURCE_LEN):
                fits_dict[fit_date][fit_freq]["sources"].append(
                    dict(zip(["ra", "ra_err", "dec", "dec_err", "flux", "flux_err", "is_main"],line[i:i+SOURCE_LEN]))
                )
    return fits_dict

def are_same(d1, d2, ignore_keys=[]):
    for key, value in d1.items():
        if key in ignore_keys:
            continue
        if d2.get(key) != value:
            return False
    return True

def merge_dicts(new_dict, old_dict):
    if old_dict == {}:
        return new_dict
    for date, bands in new_dict.items():
        for band, datasources in bands.items():
            new_sources = []
            for source in datasources["sources"]:
                matching_sources = list(filter(lambda x: are_same(x, source, ["is_main"]), old_dict.get(date, {}).get(band, {}).get("sources", [])))
                if len(matching_sources) == 1:
                    source["is_main"] = matching_sources[0].get("is_main", "")
                new_sources.append(source)
                new_dict[date][band]["sources"] = new_sources
    return new_dict

def cli():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("fitsfolder", type=Path, help="folder containing fit files")
    parser.add_argument("csvpath", type=Path, help="csv file will be saved here")
    parser.add_argument("imagesfolder", type=Path, help="folder containing fits images")
    parser.add_argument("--drawband", type=str, help="draw only images for this specific band")
    parser.add_argument("--draw", action="store_true", help="WIP: draw figures")
    parser.add_argument("--getmain", action="store_true", help="draw figures and ask for input to get main source")
    parser.add_argument("--forcegetmain", action="store_true", help="force getmain to ignore already checked sources")
    parser.add_argument("--drawangsep", type=str, help="draw angsep for specified band")
    parser.add_argument("--nogencsv", action="store_true", help="do not regenerate csv file")
    args = parser.parse_args()
    if not args.nogencsv:
        fit_dict = fit_folder_to_dict(args.fitsfolder)
        try:
            orig_dict = fit_csv_to_dict(args.csvpath)
        except FileNotFoundError:
            orig_dict = {}
        fit_dict = merge_dicts(fit_dict, orig_dict)
        fit_dict_to_csv(fit_dict, args.csvpath)
    else:
        fit_dict = fit_csv_to_dict(args.csvpath)

    if args.draw:
        drawmainsource.init()
        for date, bands in fit_dict.items():
            for band, datasources in bands.items():
                drawmainsource.draw(date, band, datasources["sources"], args.imagesfolder)
    elif args.getmain or args.drawangsep:
        drawmainsource.init()
        for date, bands in fit_dict.items():
            for band, datasources in bands.items():
                if any([s["is_main"] == "" for s in datasources["sources"]]) or args.forcegetmain:
                    sources = drawmainsource.getmain(date, band, datasources["sources"], args.imagesfolder)
                sources = datasources["sources"]
                if sources is None:
                    continue
                fit_dict[date][band]["sources"] = sources
                fit_dict_to_csv(fit_dict, args.csvpath)
    
    if args.drawangsep:
        drawangsep.draw(fit_dict, args.drawangsep, args.imagesfolder)

if __name__ == "__main__":
    cli()